/**
 * Machine-readable error codes. The API emits these; the SPAs map them to
 * localised text. Adding a code here without a translation key falls back to a
 * generic message rather than showing the raw code to a citizen.
 */

export const ERROR_CODE = Object.freeze({
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',

  UNAUTHENTICATED: 'UNAUTHENTICATED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',

  OTP_INVALID: 'OTP_INVALID',
  OTP_LOCKED: 'OTP_LOCKED',
  OTP_COOLDOWN: 'OTP_COOLDOWN',

  FORBIDDEN: 'FORBIDDEN',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',

  NOT_FOUND: 'NOT_FOUND',
  SERVICE_INACTIVE: 'SERVICE_INACTIVE',

  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  REQUEST_IS_TERMINAL: 'REQUEST_IS_TERMINAL',
  REPLY_NOT_ALLOWED: 'REPLY_NOT_ALLOWED',
  DUPLICATE_SUBMISSION: 'DUPLICATE_SUBMISSION',
  INVALID_ASSIGNEE: 'INVALID_ASSIGNEE',

  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  UNSUPPORTED_FILE_TYPE: 'UNSUPPORTED_FILE_TYPE',
  ATTACHMENT_LIMIT_EXCEEDED: 'ATTACHMENT_LIMIT_EXCEEDED',
  ATTACHMENT_REQUIRED: 'ATTACHMENT_REQUIRED',
  ATTACHMENT_UNAVAILABLE: 'ATTACHMENT_UNAVAILABLE',

  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
});

export const ERROR_CODES = Object.freeze(Object.values(ERROR_CODE));

/** i18n key per code; the SPAs resolve these against ar.json / en.json. */
export function errorTranslationKey(code) {
  return ERROR_CODES.includes(code) ? `error.${code}` : 'error.INTERNAL_ERROR';
}
